# Email (MailProperties)
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kilosavendre@gmail.com
    password: 2KilosAVendre
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  messages:
    basename: i18n/messages
